### ISSUE TITLE
Can't use

### ISSUE THREAD

**Issue by zongyuan-vale** [Teteruga/textindent#2]
hello

I added your plugin when I downloaded it and referenced it in the configuration, but it didn't appear on the editor.Everything else can be used.

eg:

extraPlugins: "textindent,uploadimage,image2,lineheight"

**Comment by Teteruga** [comment]
Hello.
I just tried it out and it seens to be working fine.

which one of those have you used? https://www.pluginsforckeditor.com/Tutorials/149/How-to-add-a-plugin-to-CKEditor/en/n149.aspx

Have you copied the textindent folder just before the plugin.js?

**Comment by zongyuan-vale** [comment]
I am in the react to use ckeditor, consulted the react-ckeditor [(https://github.com/codeslayer1/react-ckeditor)](url)

eg:

config: {
        extraPlugins: "textindent,uploadimage,image2,lineheight",
        ......
        indentation: "40"
      }

Thank.

**Comment by zongyuan-vale** [comment]
I think I've found the problem, because of the size of your ICONS.There is no normal display on the interface.

Thank.

![image](https://user-images.githubusercontent.com/33240274/36082381-d77adbb8-0fe3-11e8-8794-60a9565a1d99.png)

**Comment by Teteruga** [comment]
I just changed the images in the development see if that works for you.
if not i don't know what else i can do.

**Comment by MoonS11** [comment]
How can there be indentation in every line

**Comment by MoonS11** [comment]
![error](https://user-images.githubusercontent.com/66454858/203892333-7256c395-9268-472d-9b04-000a93459802.png)
