### ISSUE TITLE
Icon is not shown in the toolbar

### ISSUE THREAD

**Issue by chanxiaoxi** [Teteruga/textindent#4]
CKEditor Version:4.10.0

I finally found the reason:  https://github.com/Teteruga/textindent/blob/6b384d8a1c052144a60ea8b82ed5514c71fd1fe3/textindent/plugin.js#L20
There is no `ident-paragraph` in CKEditor default toolbar groups, remove it and icon is shown in toolbar.

**Comment by Teteruga** [comment]
Thanks for the heads up.
I changed the code and i have just released a new version in the ckeditor plugin page.
